namespace Markind.Siat;

public enum DocumentoSector : short
{
    Ninguno = 0,
    FacturaEstandar = 1,
    FacturaSectoresEducativos = 2,
    FacturaDeAlquilerDeBienesInmuebles = 3,
    FacturaDeComercializacionDeHidrocarburos = 4,
    FacturaDeServiciosBasicos = 5,
    FacturaProductosAlcanzadosPorElIce = 6,
    FacturaDeEntidadesFinancieras = 7,
    FacturaDeHoteles = 8,
    FacturasDeHospitalesClinicas = 9,
    FacturaDeJuegosDeAzar = 10,
    FacturaDeArtistasInternacionales = 11,
    FacturaComercialDeExportacion = 12,
    FacturaComercialDeExportaciónEnLibreConsignacion = 13,
    NotaFiscalDeZonaFranca = 14,
    NotaFiscalDeArtistasNacionales = 15,
    NotaFiscalDeComercializaciónDeAlimentosSeguridadAlimentariaYAbastecimiento = 16,
    NotaFiscalDeCompraYVentaDeMonedaExtranjera = 17,
    NotaDeCreditoDebito = 18,
    BoletoAereo = 20,
    NotaFiscalDeExportaciónDeServicioTurísticoYHospedaje = 21,
    NotaFiscalTasaCero = 22,
    FacturaHidrocarburos = 23,
    FacturaComercialDeExportaciónYpfb = 24,
    FacturaComercialDeExportaciónDeMinerales = 25,
    FacturaComercialDeLibreConsignaciónYpfb = 26,
    FacturaVentaInternaMinerales = 27,
    FacturaPrevaloradaDigital = 28,
    FacturaTelecomunicaciones = 29,
    NotaDeCreditoDebitoSfv = 30,
}