//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markind.Siat
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="Markind.Siat.ServicioFacturacion")]
    public interface ServicioFacturacion
    {
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaServicio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(solicitudServicio))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        Markind.Siat.recepcionPaqueteFacturaResponse recepcionPaqueteFactura(Markind.Siat.recepcionPaqueteFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Markind.Siat.recepcionPaqueteFacturaResponse> recepcionPaqueteFacturaAsync(Markind.Siat.recepcionPaqueteFactura request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaServicio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(solicitudServicio))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Markind.Siat.verificarComunicacionResponse verificarComunicacion(Markind.Siat.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Markind.Siat.verificarComunicacionResponse> verificarComunicacionAsync(Markind.Siat.verificarComunicacion request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaServicio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(solicitudServicio))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        Markind.Siat.recepcionFacturaResponse recepcionFactura(Markind.Siat.recepcionFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Markind.Siat.recepcionFacturaResponse> recepcionFacturaAsync(Markind.Siat.recepcionFactura request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaServicio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(solicitudServicio))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        Markind.Siat.reversionAnulacionFacturaResponse reversionAnulacionFactura(Markind.Siat.reversionAnulacionFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Markind.Siat.reversionAnulacionFacturaResponse> reversionAnulacionFacturaAsync(Markind.Siat.reversionAnulacionFactura request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaServicio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(solicitudServicio))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        Markind.Siat.validacionRecepcionMasivaFacturaResponse validacionRecepcionMasivaFactura(Markind.Siat.validacionRecepcionMasivaFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Markind.Siat.validacionRecepcionMasivaFacturaResponse> validacionRecepcionMasivaFacturaAsync(Markind.Siat.validacionRecepcionMasivaFactura request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaServicio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(solicitudServicio))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        Markind.Siat.recepcionMasivaFacturaResponse recepcionMasivaFactura(Markind.Siat.recepcionMasivaFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Markind.Siat.recepcionMasivaFacturaResponse> recepcionMasivaFacturaAsync(Markind.Siat.recepcionMasivaFactura request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaServicio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(solicitudServicio))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        Markind.Siat.verificacionEstadoFacturaResponse verificacionEstadoFactura(Markind.Siat.verificacionEstadoFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Markind.Siat.verificacionEstadoFacturaResponse> verificacionEstadoFacturaAsync(Markind.Siat.verificacionEstadoFactura request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaServicio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(solicitudServicio))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        Markind.Siat.validacionRecepcionPaqueteFacturaResponse validacionRecepcionPaqueteFactura(Markind.Siat.validacionRecepcionPaqueteFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Markind.Siat.validacionRecepcionPaqueteFacturaResponse> validacionRecepcionPaqueteFacturaAsync(Markind.Siat.validacionRecepcionPaqueteFactura request);
        
        // CODEGEN: Parameter 'RespuestaServicioFacturacion' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(respuestaServicio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(solicitudServicio))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        Markind.Siat.anulacionFacturaResponse anulacionFactura(Markind.Siat.anulacionFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Markind.Siat.anulacionFacturaResponse> anulacionFacturaAsync(Markind.Siat.anulacionFactura request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionPaquete : solicitudRecepcion
    {
        
        private int cantidadFacturasField;
        
        private long codigoEventoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadFacturas
        {
            get
            {
                return this.cantidadFacturasField;
            }
            set
            {
                this.cantidadFacturasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long codigoEvento
        {
            get
            {
                return this.codigoEventoField;
            }
            set
            {
                this.codigoEventoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class solicitudRecepcion : solicitudFacturacion
    {
        
        private byte[] archivoField;
        
        private System.DateTime fechaEnvioField;
        
        private string hashArchivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] archivo
        {
            get
            {
                return this.archivoField;
            }
            set
            {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaEnvio
        {
            get
            {
                return this.fechaEnvioField;
            }
            set
            {
                this.fechaEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string hashArchivo
        {
            get
            {
                return this.hashArchivoField;
            }
            set
            {
                this.hashArchivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudReversionAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class solicitudFacturacion : solicitudServicio
    {
        
        private int codigoDocumentoSectorField;
        
        private int codigoEmisionField;
        
        private int codigoModalidadField;
        
        private string cufdField;
        
        private string cuisField;
        
        private int tipoFacturaDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoDocumentoSector
        {
            get
            {
                return this.codigoDocumentoSectorField;
            }
            set
            {
                this.codigoDocumentoSectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoEmision
        {
            get
            {
                return this.codigoEmisionField;
            }
            set
            {
                this.codigoEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cufd
        {
            get
            {
                return this.cufdField;
            }
            set
            {
                this.cufdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int tipoFacturaDocumento
        {
            get
            {
                return this.tipoFacturaDocumentoField;
            }
            set
            {
                this.tipoFacturaDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudFacturacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudReversionAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class solicitudServicio
    {
        
        private int codigoAmbienteField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeRecepcion : mensajeServicio
    {
        
        private bool advertenciaField;
        
        private bool advertenciaFieldSpecified;
        
        private int numeroArchivoField;
        
        private bool numeroArchivoFieldSpecified;
        
        private int numeroDetalleField;
        
        private bool numeroDetalleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool advertencia
        {
            get
            {
                return this.advertenciaField;
            }
            set
            {
                this.advertenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool advertenciaSpecified
        {
            get
            {
                return this.advertenciaFieldSpecified;
            }
            set
            {
                this.advertenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroArchivo
        {
            get
            {
                return this.numeroArchivoField;
            }
            set
            {
                this.numeroArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroArchivoSpecified
        {
            get
            {
                return this.numeroArchivoFieldSpecified;
            }
            set
            {
                this.numeroArchivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroDetalle
        {
            get
            {
                return this.numeroDetalleField;
            }
            set
            {
                this.numeroDetalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDetalleSpecified
        {
            get
            {
                return this.numeroDetalleFieldSpecified;
            }
            set
            {
                this.numeroDetalleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaFacturacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class respuestaServicio
    {
        
        private mensajeServicio[] mensajeServicioListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajeServicioList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajeServicioList
        {
            get
            {
                return this.mensajeServicioListField;
            }
            set
            {
                this.mensajeServicioListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaFacturacion : respuestaServicio
    {
        
        private mensajeRecepcion[] mensajesListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeRecepcion[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaRecepcion : respuestaFacturacion
    {
        
        private string codigoDescripcionField;
        
        private int codigoEstadoField;
        
        private bool codigoEstadoFieldSpecified;
        
        private string codigoRecepcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoDescripcion
        {
            get
            {
                return this.codigoDescripcionField;
            }
            set
            {
                this.codigoDescripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoEstado
        {
            get
            {
                return this.codigoEstadoField;
            }
            set
            {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoEstadoSpecified
        {
            get
            {
                return this.codigoEstadoFieldSpecified;
            }
            set
            {
                this.codigoEstadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoRecepcion
        {
            get
            {
                return this.codigoRecepcionField;
            }
            set
            {
                this.codigoRecepcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudAnulacion : solicitudFacturacion
    {
        
        private int codigoMotivoField;
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoMotivo
        {
            get
            {
                return this.codigoMotivoField;
            }
            set
            {
                this.codigoMotivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cuf
        {
            get
            {
                return this.cufField;
            }
            set
            {
                this.cufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudVerificacionEstado : solicitudFacturacion
    {
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cuf
        {
            get
            {
                return this.cufField;
            }
            set
            {
                this.cufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudValidacionRecepcion : solicitudFacturacion
    {
        
        private string codigoRecepcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoRecepcion
        {
            get
            {
                return this.codigoRecepcionField;
            }
            set
            {
                this.codigoRecepcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudReversionAnulacion : solicitudFacturacion
    {
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cuf
        {
            get
            {
                return this.cufField;
            }
            set
            {
                this.cufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionMasiva : solicitudRecepcion
    {
        
        private int cantidadFacturasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadFacturas
        {
            get
            {
                return this.cantidadFacturasField;
            }
            set
            {
                this.cantidadFacturasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionFactura : solicitudRecepcion
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete;
        
        public recepcionPaqueteFactura()
        {
        }
        
        public recepcionPaqueteFactura(Markind.Siat.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete)
        {
            this.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionPaqueteFacturaResponse()
        {
        }
        
        public recepcionPaqueteFacturaResponse(Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacion
    {
        
        public verificarComunicacion()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public verificarComunicacionResponse()
        {
        }
        
        public verificarComunicacionResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.solicitudRecepcionFactura SolicitudServicioRecepcionFactura;
        
        public recepcionFactura()
        {
        }
        
        public recepcionFactura(Markind.Siat.solicitudRecepcionFactura SolicitudServicioRecepcionFactura)
        {
            this.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionFacturaResponse()
        {
        }
        
        public recepcionFacturaResponse(Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reversionAnulacionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class reversionAnulacionFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.solicitudReversionAnulacion SolicitudServicioReversionAnulacionFactura;
        
        public reversionAnulacionFactura()
        {
        }
        
        public reversionAnulacionFactura(Markind.Siat.solicitudReversionAnulacion SolicitudServicioReversionAnulacionFactura)
        {
            this.SolicitudServicioReversionAnulacionFactura = SolicitudServicioReversionAnulacionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reversionAnulacionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class reversionAnulacionFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion;
        
        public reversionAnulacionFacturaResponse()
        {
        }
        
        public reversionAnulacionFacturaResponse(Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionMasivaFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionMasivaFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva;
        
        public validacionRecepcionMasivaFactura()
        {
        }
        
        public validacionRecepcionMasivaFactura(Markind.Siat.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva)
        {
            this.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionMasivaFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionMasivaFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionMasivaFacturaResponse()
        {
        }
        
        public validacionRecepcionMasivaFacturaResponse(Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMasivaFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionMasivaFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva;
        
        public recepcionMasivaFactura()
        {
        }
        
        public recepcionMasivaFactura(Markind.Siat.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva)
        {
            this.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMasivaFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionMasivaFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionMasivaFacturaResponse()
        {
        }
        
        public recepcionMasivaFacturaResponse(Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionEstadoFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificacionEstadoFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura;
        
        public verificacionEstadoFactura()
        {
        }
        
        public verificacionEstadoFactura(Markind.Siat.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura)
        {
            this.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionEstadoFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificacionEstadoFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion;
        
        public verificacionEstadoFacturaResponse()
        {
        }
        
        public verificacionEstadoFacturaResponse(Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete;
        
        public validacionRecepcionPaqueteFactura()
        {
        }
        
        public validacionRecepcionPaqueteFactura(Markind.Siat.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete)
        {
            this.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionPaqueteFacturaResponse()
        {
        }
        
        public validacionRecepcionPaqueteFacturaResponse(Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.solicitudAnulacion SolicitudServicioAnulacionFactura;
        
        public anulacionFactura()
        {
        }
        
        public anulacionFactura(Markind.Siat.solicitudAnulacion SolicitudServicioAnulacionFactura)
        {
            this.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion;
        
        public anulacionFacturaResponse()
        {
        }
        
        public anulacionFacturaResponse(Markind.Siat.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ServicioFacturacionChannel : Markind.Siat.ServicioFacturacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioFacturacionClient : System.ServiceModel.ClientBase<Markind.Siat.ServicioFacturacion>, Markind.Siat.ServicioFacturacion
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioFacturacionClient() : 
                base(ServicioFacturacionClient.GetDefaultBinding(), ServicioFacturacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioFacturacionPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioFacturacionClient.GetBindingForEndpoint(endpointConfiguration), ServicioFacturacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioFacturacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioFacturacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markind.Siat.recepcionPaqueteFacturaResponse Markind.Siat.ServicioFacturacion.recepcionPaqueteFactura(Markind.Siat.recepcionPaqueteFactura request)
        {
            return base.Channel.recepcionPaqueteFactura(request);
        }
        
        public Markind.Siat.respuestaRecepcion recepcionPaqueteFactura(Markind.Siat.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete)
        {
            Markind.Siat.recepcionPaqueteFactura inValue = new Markind.Siat.recepcionPaqueteFactura();
            inValue.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
            Markind.Siat.recepcionPaqueteFacturaResponse retVal = ((Markind.Siat.ServicioFacturacion)(this)).recepcionPaqueteFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markind.Siat.recepcionPaqueteFacturaResponse> Markind.Siat.ServicioFacturacion.recepcionPaqueteFacturaAsync(Markind.Siat.recepcionPaqueteFactura request)
        {
            return base.Channel.recepcionPaqueteFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markind.Siat.recepcionPaqueteFacturaResponse> recepcionPaqueteFacturaAsync(Markind.Siat.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete)
        {
            Markind.Siat.recepcionPaqueteFactura inValue = new Markind.Siat.recepcionPaqueteFactura();
            inValue.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
            return ((Markind.Siat.ServicioFacturacion)(this)).recepcionPaqueteFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markind.Siat.verificarComunicacionResponse Markind.Siat.ServicioFacturacion.verificarComunicacion(Markind.Siat.verificarComunicacion request)
        {
            return base.Channel.verificarComunicacion(request);
        }
        
        public int verificarComunicacion()
        {
            Markind.Siat.verificarComunicacion inValue = new Markind.Siat.verificarComunicacion();
            Markind.Siat.verificarComunicacionResponse retVal = ((Markind.Siat.ServicioFacturacion)(this)).verificarComunicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markind.Siat.verificarComunicacionResponse> Markind.Siat.ServicioFacturacion.verificarComunicacionAsync(Markind.Siat.verificarComunicacion request)
        {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markind.Siat.verificarComunicacionResponse> verificarComunicacionAsync()
        {
            Markind.Siat.verificarComunicacion inValue = new Markind.Siat.verificarComunicacion();
            return ((Markind.Siat.ServicioFacturacion)(this)).verificarComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markind.Siat.recepcionFacturaResponse Markind.Siat.ServicioFacturacion.recepcionFactura(Markind.Siat.recepcionFactura request)
        {
            return base.Channel.recepcionFactura(request);
        }
        
        public Markind.Siat.respuestaRecepcion recepcionFactura(Markind.Siat.solicitudRecepcionFactura SolicitudServicioRecepcionFactura)
        {
            Markind.Siat.recepcionFactura inValue = new Markind.Siat.recepcionFactura();
            inValue.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
            Markind.Siat.recepcionFacturaResponse retVal = ((Markind.Siat.ServicioFacturacion)(this)).recepcionFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markind.Siat.recepcionFacturaResponse> Markind.Siat.ServicioFacturacion.recepcionFacturaAsync(Markind.Siat.recepcionFactura request)
        {
            return base.Channel.recepcionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markind.Siat.recepcionFacturaResponse> recepcionFacturaAsync(Markind.Siat.solicitudRecepcionFactura SolicitudServicioRecepcionFactura)
        {
            Markind.Siat.recepcionFactura inValue = new Markind.Siat.recepcionFactura();
            inValue.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
            return ((Markind.Siat.ServicioFacturacion)(this)).recepcionFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markind.Siat.reversionAnulacionFacturaResponse Markind.Siat.ServicioFacturacion.reversionAnulacionFactura(Markind.Siat.reversionAnulacionFactura request)
        {
            return base.Channel.reversionAnulacionFactura(request);
        }
        
        public Markind.Siat.respuestaRecepcion reversionAnulacionFactura(Markind.Siat.solicitudReversionAnulacion SolicitudServicioReversionAnulacionFactura)
        {
            Markind.Siat.reversionAnulacionFactura inValue = new Markind.Siat.reversionAnulacionFactura();
            inValue.SolicitudServicioReversionAnulacionFactura = SolicitudServicioReversionAnulacionFactura;
            Markind.Siat.reversionAnulacionFacturaResponse retVal = ((Markind.Siat.ServicioFacturacion)(this)).reversionAnulacionFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markind.Siat.reversionAnulacionFacturaResponse> Markind.Siat.ServicioFacturacion.reversionAnulacionFacturaAsync(Markind.Siat.reversionAnulacionFactura request)
        {
            return base.Channel.reversionAnulacionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markind.Siat.reversionAnulacionFacturaResponse> reversionAnulacionFacturaAsync(Markind.Siat.solicitudReversionAnulacion SolicitudServicioReversionAnulacionFactura)
        {
            Markind.Siat.reversionAnulacionFactura inValue = new Markind.Siat.reversionAnulacionFactura();
            inValue.SolicitudServicioReversionAnulacionFactura = SolicitudServicioReversionAnulacionFactura;
            return ((Markind.Siat.ServicioFacturacion)(this)).reversionAnulacionFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markind.Siat.validacionRecepcionMasivaFacturaResponse Markind.Siat.ServicioFacturacion.validacionRecepcionMasivaFactura(Markind.Siat.validacionRecepcionMasivaFactura request)
        {
            return base.Channel.validacionRecepcionMasivaFactura(request);
        }
        
        public Markind.Siat.respuestaRecepcion validacionRecepcionMasivaFactura(Markind.Siat.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva)
        {
            Markind.Siat.validacionRecepcionMasivaFactura inValue = new Markind.Siat.validacionRecepcionMasivaFactura();
            inValue.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
            Markind.Siat.validacionRecepcionMasivaFacturaResponse retVal = ((Markind.Siat.ServicioFacturacion)(this)).validacionRecepcionMasivaFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markind.Siat.validacionRecepcionMasivaFacturaResponse> Markind.Siat.ServicioFacturacion.validacionRecepcionMasivaFacturaAsync(Markind.Siat.validacionRecepcionMasivaFactura request)
        {
            return base.Channel.validacionRecepcionMasivaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markind.Siat.validacionRecepcionMasivaFacturaResponse> validacionRecepcionMasivaFacturaAsync(Markind.Siat.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva)
        {
            Markind.Siat.validacionRecepcionMasivaFactura inValue = new Markind.Siat.validacionRecepcionMasivaFactura();
            inValue.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
            return ((Markind.Siat.ServicioFacturacion)(this)).validacionRecepcionMasivaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markind.Siat.recepcionMasivaFacturaResponse Markind.Siat.ServicioFacturacion.recepcionMasivaFactura(Markind.Siat.recepcionMasivaFactura request)
        {
            return base.Channel.recepcionMasivaFactura(request);
        }
        
        public Markind.Siat.respuestaRecepcion recepcionMasivaFactura(Markind.Siat.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva)
        {
            Markind.Siat.recepcionMasivaFactura inValue = new Markind.Siat.recepcionMasivaFactura();
            inValue.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
            Markind.Siat.recepcionMasivaFacturaResponse retVal = ((Markind.Siat.ServicioFacturacion)(this)).recepcionMasivaFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markind.Siat.recepcionMasivaFacturaResponse> Markind.Siat.ServicioFacturacion.recepcionMasivaFacturaAsync(Markind.Siat.recepcionMasivaFactura request)
        {
            return base.Channel.recepcionMasivaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markind.Siat.recepcionMasivaFacturaResponse> recepcionMasivaFacturaAsync(Markind.Siat.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva)
        {
            Markind.Siat.recepcionMasivaFactura inValue = new Markind.Siat.recepcionMasivaFactura();
            inValue.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
            return ((Markind.Siat.ServicioFacturacion)(this)).recepcionMasivaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markind.Siat.verificacionEstadoFacturaResponse Markind.Siat.ServicioFacturacion.verificacionEstadoFactura(Markind.Siat.verificacionEstadoFactura request)
        {
            return base.Channel.verificacionEstadoFactura(request);
        }
        
        public Markind.Siat.respuestaRecepcion verificacionEstadoFactura(Markind.Siat.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura)
        {
            Markind.Siat.verificacionEstadoFactura inValue = new Markind.Siat.verificacionEstadoFactura();
            inValue.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
            Markind.Siat.verificacionEstadoFacturaResponse retVal = ((Markind.Siat.ServicioFacturacion)(this)).verificacionEstadoFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markind.Siat.verificacionEstadoFacturaResponse> Markind.Siat.ServicioFacturacion.verificacionEstadoFacturaAsync(Markind.Siat.verificacionEstadoFactura request)
        {
            return base.Channel.verificacionEstadoFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markind.Siat.verificacionEstadoFacturaResponse> verificacionEstadoFacturaAsync(Markind.Siat.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura)
        {
            Markind.Siat.verificacionEstadoFactura inValue = new Markind.Siat.verificacionEstadoFactura();
            inValue.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
            return ((Markind.Siat.ServicioFacturacion)(this)).verificacionEstadoFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markind.Siat.validacionRecepcionPaqueteFacturaResponse Markind.Siat.ServicioFacturacion.validacionRecepcionPaqueteFactura(Markind.Siat.validacionRecepcionPaqueteFactura request)
        {
            return base.Channel.validacionRecepcionPaqueteFactura(request);
        }
        
        public Markind.Siat.respuestaRecepcion validacionRecepcionPaqueteFactura(Markind.Siat.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete)
        {
            Markind.Siat.validacionRecepcionPaqueteFactura inValue = new Markind.Siat.validacionRecepcionPaqueteFactura();
            inValue.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
            Markind.Siat.validacionRecepcionPaqueteFacturaResponse retVal = ((Markind.Siat.ServicioFacturacion)(this)).validacionRecepcionPaqueteFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markind.Siat.validacionRecepcionPaqueteFacturaResponse> Markind.Siat.ServicioFacturacion.validacionRecepcionPaqueteFacturaAsync(Markind.Siat.validacionRecepcionPaqueteFactura request)
        {
            return base.Channel.validacionRecepcionPaqueteFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markind.Siat.validacionRecepcionPaqueteFacturaResponse> validacionRecepcionPaqueteFacturaAsync(Markind.Siat.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete)
        {
            Markind.Siat.validacionRecepcionPaqueteFactura inValue = new Markind.Siat.validacionRecepcionPaqueteFactura();
            inValue.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
            return ((Markind.Siat.ServicioFacturacion)(this)).validacionRecepcionPaqueteFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Markind.Siat.anulacionFacturaResponse Markind.Siat.ServicioFacturacion.anulacionFactura(Markind.Siat.anulacionFactura request)
        {
            return base.Channel.anulacionFactura(request);
        }
        
        public Markind.Siat.respuestaRecepcion anulacionFactura(Markind.Siat.solicitudAnulacion SolicitudServicioAnulacionFactura)
        {
            Markind.Siat.anulacionFactura inValue = new Markind.Siat.anulacionFactura();
            inValue.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
            Markind.Siat.anulacionFacturaResponse retVal = ((Markind.Siat.ServicioFacturacion)(this)).anulacionFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Markind.Siat.anulacionFacturaResponse> Markind.Siat.ServicioFacturacion.anulacionFacturaAsync(Markind.Siat.anulacionFactura request)
        {
            return base.Channel.anulacionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Markind.Siat.anulacionFacturaResponse> anulacionFacturaAsync(Markind.Siat.solicitudAnulacion SolicitudServicioAnulacionFactura)
        {
            Markind.Siat.anulacionFactura inValue = new Markind.Siat.anulacionFactura();
            inValue.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
            return ((Markind.Siat.ServicioFacturacion)(this)).anulacionFacturaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionPort))
            {
                return new System.ServiceModel.EndpointAddress("https://pilotosiatservicios.impuestos.gob.bo/v1/ServicioFacturacionComputarizada");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioFacturacionClient.GetBindingForEndpoint(EndpointConfiguration.ServicioFacturacionPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioFacturacionClient.GetEndpointAddress(EndpointConfiguration.ServicioFacturacionPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioFacturacionPort,
        }
    }
}
